function Hd = filter4
%FILTER4 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 11-May-2025 05:16:53

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency

N    = 250;      % Order
Fc1  = 200;      % First Cutoff Frequency
Fc2  = 14800;    % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
