function Hd = filter2
%FILTER2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 11-May-2025 04:36:46

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency

N     = 200;    % Order
Fpass = 14700;  % Passband Frequency
Fstop = 15100;  % Stopband Frequency
Wpass = 1;      % Passband Weight
Wstop = 100;    % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
