function Hd = filter3
%FILTER3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 11-May-2025 04:55:43

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 32;  % Sampling Frequency

N    = 250;      % Order
Fc1  = 14.8;     % First Cutoff Frequency
Fc2  = 15.6;     % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'stop', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
